apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
    spec:
      containers:
      - name: news-backend
        image: news-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: news-backend-service
spec:
  selector:
    app: news-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
